# Generated by Django 6.0.6 on 2026-07-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email_address",
            field=models.CharField(default="test@example.com", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="shif_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
